window.KANJI_DATA = [
  {id:1,kanji:'山',reading:'やま',meaning:'montanha',lesson:1,page:25,hint:'Tem relação com <ruby>やま<rt>montanha</rt></ruby>.'},
  {id:2,kanji:'川',reading:'かわ',meaning:'rio',lesson:1,page:25,hint:'Tem relação com <ruby>かわ<rt>rio</rt></ruby>.'},
  {id:3,kanji:'田',reading:'た',meaning:'arrozal',lesson:1,page:25,hint:'Tem relação com <ruby>た<rt>arrozal</rt></ruby>, um campo de arroz.'},
  {id:4,kanji:'日',reading:'ひ',meaning:'sol',lesson:1,page:25,hint:'Tem relação com <ruby>ひ<rt>sol</rt></ruby>.'},
  {id:5,kanji:'月',reading:'つき',meaning:'lua',lesson:1,page:25,hint:'Tem relação com <ruby>つき<rt>lua</rt></ruby>.'},
  {id:6,kanji:'火',reading:'ひ',meaning:'fogo',lesson:1,page:25,hint:'Tem relação com <ruby>ひ<rt>fogo</rt></ruby>.'},
  {id:7,kanji:'水',reading:'みず',meaning:'água',lesson:1,page:25,hint:'Tem relação com <ruby>みず<rt>água</rt></ruby>.'},
  {id:8,kanji:'木',reading:'き',meaning:'árvore',lesson:1,page:25,hint:'Tem relação com <ruby>き<rt>árvore</rt></ruby>.'},
  {id:9,kanji:'金',reading:'きん',meaning:'ouro',lesson:1,page:25,hint:'Tem relação com <ruby>きん<rt>ouro</rt></ruby>.'},
  {id:10,kanji:'土',reading:'つち',meaning:'terra',lesson:1,page:25,hint:'Tem relação com <ruby>つち<rt>terra</rt></ruby>.'},

  {id:11,kanji:'一',reading:'いち',meaning:'um(a)',lesson:2,page:31,hint:'É o número <ruby>いち<rt>um</rt></ruby>.'},
  {id:12,kanji:'二',reading:'に',meaning:'dois/duas',lesson:2,page:31,hint:'É o número <ruby>に<rt>dois</rt></ruby>.'},
  {id:13,kanji:'三',reading:'さん',meaning:'três',lesson:2,page:31,hint:'É o número <ruby>さん<rt>três</rt></ruby>.'},
  {id:14,kanji:'四',reading:'よん・し',meaning:'quatro',lesson:2,page:31,hint:'É o número <ruby>よん</ruby> / <ruby>し<rt>quatro</rt></ruby>.'},
  {id:15,kanji:'五',reading:'ご',meaning:'cinco',lesson:2,page:31,hint:'É o número <ruby>ご<rt>cinco</rt></ruby>.'},
  {id:16,kanji:'六',reading:'ろく',meaning:'seis',lesson:2,page:31,hint:'É o número <ruby>ろく<rt>seis</rt></ruby>.'},
  {id:17,kanji:'七',reading:'なな・しち',meaning:'sete',lesson:2,page:31,hint:'É o número <ruby>なな</ruby> / <ruby>しち<rt>sete</rt></ruby>.'},
  {id:18,kanji:'八',reading:'はち',meaning:'oito',lesson:2,page:31,hint:'É o número <ruby>はち<rt>oito</rt></ruby>.'},
  {id:19,kanji:'九',reading:'きゅう',meaning:'nove',lesson:2,page:31,hint:'É o número <ruby>きゅう<rt>nove</rt></ruby>.'},
  {id:20,kanji:'十',reading:'じゅう',meaning:'dez',lesson:2,page:31,hint:'É o número <ruby>じゅう<rt>dez</rt></ruby>.'},

  {id:21,kanji:'百',reading:'ひゃく',meaning:'cem',lesson:3,page:37,hint:'Tem relação com <ruby>ひゃく<rt>cem</rt></ruby>.'},
  {id:22,kanji:'千',reading:'せん',meaning:'mil',lesson:3,page:37,hint:'Tem relação com <ruby>せん<rt>mil</rt></ruby>.'},
  {id:23,kanji:'万',reading:'まん',meaning:'dez mil',lesson:3,page:37,hint:'Tem relação com <ruby>まん<rt>dez mil</rt></ruby>.'},
  {id:24,kanji:'円',reading:'えん',meaning:'iene / círculo',lesson:3,page:37,hint:'Tem relação com <ruby>えん<rt>iene</rt></ruby> e também com a ideia de círculo.'},
  {id:25,kanji:'年',reading:'とし',meaning:'ano',lesson:3,page:37,hint:'Tem relação com <ruby>とし<rt>ano</rt></ruby>.'},
  {id:26,kanji:'上',reading:'うえ',meaning:'(a)cima',lesson:3,page:37,hint:'Tem relação com <ruby>うえ<rt>cima</rt></ruby>.'},
  {id:27,kanji:'下',reading:'した',meaning:'(a)baixo',lesson:3,page:37,hint:'Tem relação com <ruby>した<rt>baixo</rt></ruby>.'},
  {id:28,kanji:'中',reading:'なか',meaning:'dentro / meio',lesson:3,page:37,hint:'Tem relação com <ruby>なか<rt>dentro</rt></ruby>, o meio.'},
  {id:29,kanji:'半',reading:'はんぶん',meaning:'metade',lesson:3,page:37,hint:'Tem relação com <ruby>はんぶん<rt>metade</rt></ruby>.'},
  {id:30,kanji:'分',reading:'わける',meaning:'dividir / parte',lesson:3,page:37,hint:'Tem relação com <ruby>わける<rt>dividir</rt></ruby>.'},

  {id:31,kanji:'人',reading:'ひと',meaning:'pessoa',lesson:4,page:45,hint:'Tem relação com <ruby>ひと<rt>pessoa</rt></ruby>.'},
  {id:32,kanji:'子',reading:'こ',meaning:'criança',lesson:4,page:45,hint:'Tem relação com <ruby>こ<rt>criança</rt></ruby>.'},
  {id:33,kanji:'女',reading:'おんな',meaning:'mulher',lesson:4,page:45,hint:'Tem relação com <ruby>おんな<rt>mulher</rt></ruby>.'},
  {id:34,kanji:'男',reading:'おとこ',meaning:'homem',lesson:4,page:45,hint:'Tem relação com <ruby>おとこ<rt>homem</rt></ruby>.'},
  {id:35,kanji:'目',reading:'め',meaning:'olho',lesson:4,page:45,hint:'Tem relação com <ruby>め<rt>olho</rt></ruby>.'},
  {id:36,kanji:'口',reading:'くち',meaning:'boca',lesson:4,page:45,hint:'Tem relação com <ruby>くち<rt>boca</rt></ruby>.'},
  {id:37,kanji:'耳',reading:'みみ',meaning:'orelha',lesson:4,page:45,hint:'Tem relação com <ruby>みみ<rt>orelha</rt></ruby>.'},
  {id:38,kanji:'手',reading:'て',meaning:'mão',lesson:4,page:45,hint:'Tem relação com <ruby>て<rt>mão</rt></ruby>.'},
  {id:39,kanji:'足',reading:'あし',meaning:'pé',lesson:4,page:45,hint:'Tem relação com <ruby>あし<rt>pé</rt></ruby>.'},
  {id:40,kanji:'力',reading:'ちから',meaning:'força',lesson:4,page:45,hint:'Tem relação com <ruby>ちから<rt>força</rt></ruby>.'},

  {id:41,kanji:'父',reading:'ちち',meaning:'pai',lesson:5,page:52,hint:'Tem relação com <ruby>ちち<rt>pai</rt></ruby>.'},
  {id:42,kanji:'母',reading:'はは',meaning:'mãe',lesson:5,page:52,hint:'Tem relação com <ruby>はは<rt>mãe</rt></ruby>.'},
  {id:43,kanji:'先',reading:'さき',meaning:'anterior / antes',lesson:5,page:52,hint:'Tem relação com <ruby>さき<rt>antes</rt></ruby>, algo anterior.'},
  {id:44,kanji:'生',reading:'うまれる・いきる',meaning:'nascer / viver',lesson:5,page:53,hint:'Tem relação com <ruby>うまれる<rt>nascer</rt></ruby> e com vida.'},
  {id:45,kanji:'学',reading:'べんきょうする',meaning:'estudar',lesson:5,page:53,hint:'Tem relação com <ruby>べんきょうする<rt>estudar</rt></ruby>.'},
  {id:46,kanji:'校',reading:'がっこう',meaning:'escola',lesson:5,page:53,hint:'Tem relação com <ruby>がっこう<rt>escola</rt></ruby>.'},
  {id:47,kanji:'友',reading:'ともだち',meaning:'amigo',lesson:5,page:54,hint:'Tem relação com <ruby>ともだち<rt>amigo</rt></ruby>.'},
  {id:48,kanji:'本',reading:'ほん・もと',meaning:'livro / origem',lesson:5,page:54,hint:'Tem relação com <ruby>ほん<rt>livro</rt></ruby> e também com a ideia de origem (<ruby>もと</ruby>).' },
  {id:49,kanji:'毎',reading:'まい',meaning:'cada',lesson:5,page:54,hint:'Tem relação com <ruby>まい<rt>cada</rt></ruby>.'},
  {id:50,kanji:'何',reading:'なに・なん',meaning:'o que',lesson:5,page:55,hint:'Tem relação com <ruby>なに<rt>o que</rt></ruby>.'},

  {id:51,kanji:'前',reading:'まえ',meaning:'frente / antes',lesson:6,page:58,hint:'Tem relação com <ruby>まえ<rt>frente</rt></ruby>.'},
  {id:52,kanji:'後',reading:'うしろ・あと',meaning:'atrás / depois',lesson:6,page:58,hint:'Tem relação com <ruby>うしろ<rt>atrás</rt></ruby> e <ruby>あと<rt>depois</rt></ruby>.'},
  {id:53,kanji:'外',reading:'そと',meaning:'fora',lesson:6,page:58,hint:'Tem relação com <ruby>そと<rt>fora</rt></ruby>.'},
  {id:54,kanji:'左',reading:'ひだり',meaning:'esquerda',lesson:6,page:59,hint:'Tem relação com <ruby>ひだり<rt>esquerda</rt></ruby>.'},
  {id:55,kanji:'右',reading:'みぎ',meaning:'direita',lesson:6,page:59,hint:'Tem relação com <ruby>みぎ<rt>direita</rt></ruby>.'},
  {id:56,kanji:'東',reading:'ひがし',meaning:'leste',lesson:6,page:59,hint:'Tem relação com <ruby>ひがし<rt>leste</rt></ruby>.'},
  {id:57,kanji:'西',reading:'にし',meaning:'oeste',lesson:6,page:60,hint:'Tem relação com <ruby>にし<rt>oeste</rt></ruby>.'},
  {id:58,kanji:'南',reading:'みなみ',meaning:'sul',lesson:6,page:60,hint:'Tem relação com <ruby>みなみ<rt>sul</rt></ruby>.'},
  {id:59,kanji:'北',reading:'きた',meaning:'norte',lesson:6,page:60,hint:'Tem relação com <ruby>きた<rt>norte</rt></ruby>.'},
  {id:60,kanji:'名',reading:'なまえ',meaning:'nome',lesson:6,page:61,hint:'Tem relação com <ruby>なまえ<rt>nome</rt></ruby>.'},

  {id:61,kanji:'牛',reading:'うし',meaning:'boi',lesson:7,page:65,hint:'Tem relação com <ruby>うし<rt>boi</rt></ruby>.'},
  {id:62,kanji:'馬',reading:'うま',meaning:'cavalo',lesson:7,page:65,hint:'Tem relação com <ruby>うま<rt>cavalo</rt></ruby>.'},
  {id:63,kanji:'魚',reading:'さかな',meaning:'peixe',lesson:7,page:65,hint:'Tem relação com <ruby>さかな<rt>peixe</rt></ruby>.'},
  {id:64,kanji:'貝',reading:'かい',meaning:'marisco',lesson:7,page:65,hint:'Tem relação com <ruby>かい<rt>marisco</rt></ruby>.'},
  {id:65,kanji:'雨',reading:'あめ',meaning:'chuva',lesson:7,page:65,hint:'Tem relação com <ruby>あめ<rt>chuva</rt></ruby>.'},
  {id:66,kanji:'天',reading:'てん',meaning:'céu',lesson:7,page:65,hint:'Tem relação com <ruby>てん<rt>céu</rt></ruby>.'},
  {id:67,kanji:'気',reading:'き',meaning:'ar',lesson:7,page:65,hint:'Tem relação com <ruby>き<rt>ar</rt></ruby>.'},
  {id:68,kanji:'車',reading:'くるま',meaning:'carro',lesson:7,page:65,hint:'Tem relação com <ruby>くるま<rt>carro</rt></ruby>.'},
  {id:69,kanji:'門',reading:'もん',meaning:'portal',lesson:7,page:65,hint:'Tem relação com <ruby>もん<rt>portal</rt></ruby>.'},
  {id:70,kanji:'午',reading:'ご',meaning:'meio-dia',lesson:7,page:65,hint:'Tem relação com <ruby>ご<rt>meio-dia</rt></ruby>.'},

  {id:71,kanji:'大',reading:'おおきい',meaning:'grande',lesson:8,page:71,hint:'Tem relação com <ruby>おおきい<rt>grande</rt></ruby>.'},
  {id:72,kanji:'小',reading:'ちいさい',meaning:'pequeno',lesson:8,page:71,hint:'Tem relação com <ruby>ちいさい<rt>pequeno</rt></ruby>.'},
  {id:73,kanji:'高',reading:'たかい',meaning:'alto',lesson:8,page:71,hint:'Tem relação com <ruby>たかい<rt>alto</rt></ruby>.'},
  {id:74,kanji:'安',reading:'あんしん',meaning:'seguro',lesson:8,page:71,hint:'Tem relação com <ruby>あんしん<rt>seguro</rt></ruby>.'},
  {id:75,kanji:'新',reading:'あたらしい',meaning:'novo',lesson:8,page:71,hint:'Tem relação com <ruby>あたらしい<rt>novo</rt></ruby>.'},
  {id:76,kanji:'古',reading:'ふるい',meaning:'velho',lesson:8,page:71,hint:'Tem relação com <ruby>ふるい<rt>velho</rt></ruby>.'},
  {id:77,kanji:'長',reading:'ながい',meaning:'longo',lesson:8,page:71,hint:'Tem relação com <ruby>ながい<rt>longo</rt></ruby>.'},
  {id:78,kanji:'多',reading:'おおい',meaning:'bastante',lesson:8,page:71,hint:'Tem relação com <ruby>おおい<rt>muito</rt></ruby>.'},
  {id:79,kanji:'少',reading:'すくない',meaning:'pouco',lesson:8,page:71,hint:'Tem relação com <ruby>すくない<rt>pouco</rt></ruby>.'},
  {id:80,kanji:'早',reading:'はやい',meaning:'cedo',lesson:8,page:71,hint:'Tem relação com <ruby>はやい<rt>cedo</rt></ruby>.'},

  {id:81,kanji:'行',reading:'いきます',meaning:'ir',lesson:9,page:77,hint:'Tem relação com <ruby>いきます<rt>ir</rt></ruby>.'},
  {id:82,kanji:'来',reading:'きます',meaning:'vir',lesson:9,page:77,hint:'Tem relação com <ruby>きます<rt>vir</rt></ruby>.'},
  {id:83,kanji:'食',reading:'たべます',meaning:'comer',lesson:9,page:77,hint:'Tem relação com <ruby>たべます<rt>comer</rt></ruby>.'},
  {id:84,kanji:'見',reading:'みます',meaning:'ver',lesson:9,page:77,hint:'Tem relação com <ruby>みます<rt>ver</rt></ruby>.'},
  {id:85,kanji:'入',reading:'はいります',meaning:'entrar',lesson:9,page:77,hint:'Tem relação com <ruby>はいります<rt>entrar</rt></ruby>.'},
  {id:86,kanji:'出',reading:'でます',meaning:'sair',lesson:9,page:77,hint:'Tem relação com <ruby>でます<rt>sair</rt></ruby>.'},
  {id:87,kanji:'立',reading:'たちます',meaning:'ficar de pé',lesson:9,page:77,hint:'Tem relação com <ruby>たちます<rt>ficar de pé</rt></ruby>.'},
  {id:88,kanji:'書',reading:'かきます',meaning:'escrever',lesson:9,page:77,hint:'Tem relação com <ruby>かきます<rt>escrever</rt></ruby>.'},
  {id:89,kanji:'言',reading:'いいます',meaning:'dizer',lesson:9,page:77,hint:'Tem relação com <ruby>いいます<rt>dizer</rt></ruby>.'},
  {id:90,kanji:'飲',reading:'のみます',meaning:'beber',lesson:9,page:77,hint:'Tem relação com <ruby>のみます<rt>beber</rt></ruby>.'},

  {id:91,kanji:'話',reading:'はなす',meaning:'conversar',lesson:10,page:86,hint:'Tem relação com <ruby>はなす<rt>conversar</rt></ruby>.'},
  {id:92,kanji:'読',reading:'よむ',meaning:'ler',lesson:10,page:86,hint:'Tem relação com <ruby>よむ<rt>ler</rt></ruby>.'},
  {id:93,kanji:'語',reading:'ことば',meaning:'palavra / fala',lesson:10,page:86,hint:'Tem relação com <ruby>ことば<rt>palavra</rt></ruby>.'},
  {id:94,kanji:'間',reading:'あいだ',meaning:'entre',lesson:10,page:87,hint:'Tem relação com <ruby>あいだ<rt>entre</rt></ruby>.'},
  {id:95,kanji:'聞',reading:'きく',meaning:'ouvir',lesson:10,page:87,hint:'Tem relação com <ruby>きく<rt>ouvir</rt></ruby>.'},
  {id:96,kanji:'買',reading:'かう',meaning:'comprar',lesson:10,page:87,hint:'Tem relação com <ruby>かう<rt>comprar</rt></ruby>.'},
  {id:97,kanji:'休',reading:'やすむ',meaning:'descansar',lesson:10,page:88,hint:'Tem relação com <ruby>やすむ<rt>descansar</rt></ruby>.'},
  {id:98,kanji:'時',reading:'じかん',meaning:'tempo',lesson:10,page:88,hint:'Tem relação com <ruby>じかん<rt>tempo</rt></ruby>.'},
  {id:99,kanji:'週',reading:'しゅう',meaning:'semana',lesson:10,page:88,hint:'Tem relação com <ruby>しゅう<rt>semana</rt></ruby>.'},
  {id:100,kanji:'道',reading:'みち',meaning:'caminho',lesson:10,page:89,hint:'Tem relação com <ruby>みち<rt>caminho</rt></ruby>.'},

  {id:101,kanji:'今',reading:'いま',meaning:'agora',lesson:11,page:92,hint:'Tem relação com <ruby>いま<rt>agora</rt></ruby>.'},
  {id:102,kanji:'会',reading:'あう',meaning:'encontrar',lesson:11,page:92,hint:'Tem relação com <ruby>あう<rt>encontrar</rt></ruby>.'},
  {id:103,kanji:'社',reading:'かいしゃ',meaning:'empresa',lesson:11,page:92,hint:'Tem relação com <ruby>かいしゃ<rt>empresa</rt></ruby>.'},
  {id:104,kanji:'店',reading:'みせ',meaning:'loja',lesson:11,page:93,hint:'Tem relação com <ruby>みせ<rt>loja</rt></ruby>.'},
  {id:105,kanji:'駅',reading:'えき',meaning:'estação',lesson:11,page:93,hint:'Tem relação com <ruby>えき<rt>estação</rt></ruby>.'},
  {id:106,kanji:'花',reading:'はな',meaning:'flor',lesson:11,page:93,hint:'Tem relação com <ruby>はな<rt>flor</rt></ruby>.'},
  {id:107,kanji:'国',reading:'くに',meaning:'país',lesson:11,page:94,hint:'Tem relação com <ruby>くに<rt>país</rt></ruby>.'},
  {id:108,kanji:'白',reading:'しろ',meaning:'branco',lesson:11,page:94,hint:'Tem relação com <ruby>しろ<rt>branco</rt></ruby>.'},
  {id:109,kanji:'空',reading:'そら',meaning:'céu',lesson:11,page:94,hint:'Tem relação com <ruby>そら<rt>céu</rt></ruby> e também com vazio.'},
  {id:110,kanji:'電',reading:'でんき',meaning:'eletricidade',lesson:11,page:95,hint:'Tem relação com <ruby>でんき<rt>eletricidade</rt></ruby>.'}
];
